name: check_syntax

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
      exclude:
        - os: ubuntu-latest
          python-version: "3.10"

    steps:
    - uses: actions/checkout@v3

    - name: Aktualizacja pip
      run: |
        python -m pip install --upgrade pip

    - name: instalacja flake'a i unittest
      run: |
        pip install flake8
        pip install unittest

    - name: wyswietlanie wersji
      run: python --version

    - name: uruchomienie flake'a
      run: flake8

    - name: uruchomienie unittest
      run: python -m unittest discover