name: check_syntax

on:
  push:
    branches: [ "check_syntax" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: runs-on: ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11",]

    steps:
    - uses: actions/checkout@v3
    
    - name: aktualizacja pip i flake
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Wyswietlenie wersji
      run:  python --version
    - name: Uruchomienie flake8
      run:  flake8
