name: check_syntax

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Aktualizacja pip
      run: |
        python -m pip install --upgrade pip

    - name: Instalacja flake8
      run: |
        pip install flake8

    - name: Wyświetlanie wersji Pythona
      run: python --version

    - name: Uruchomienie flake8
      run: flake8

    - name: Uruchomienie unittest
      run: python -m unittest discover

  build_ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Aktualizacja pip
      run: |
        python3 -m pip install --upgrade pip

    - name: Instalacja flake i unittest
      run: |
        pip3 install flake8
        pip3 install unittest

    - name: Wyświetlanie wersji Pythona
      run: python3 --version

    - name: Uruchomienie flake8
      run: flake8

    - name: Uruchomienie unittest
      run: python3 -m unittest discover